export type CommCategory = 'appointments' | 'field' | 'payments' | 'retention';
export type CommChannel = 'email' | 'sms' | 'email_sms';

export type CommunicationTemplate = {
  id: string;
  event_key: string;
  name: string;
  category: CommCategory;
  timing_label: string;
  send_delay_minutes: number;
  email_enabled: boolean;
  sms_enabled: boolean;
  is_enabled: boolean;
  subject: string;
  body: string;
  sms_body: string;
  status_step: 'booked' | 'confirmed' | 'en_route' | 'in_progress' | 'complete';
};

export const COMM_VARIABLES = [
  '{customer_first_name}',
  '{detailer_name}',
  '{vehicle}',
  '{service}',
  '{appointment_time}',
  '{price}',
  '{eta}',
  '{portal_link}',
] as const;

export const COMM_GROUPS: { id: CommCategory; title: string }[] = [
  { id: 'appointments', title: 'Appointment notifications' },
  { id: 'field', title: 'Day-of-service updates' },
  { id: 'payments', title: 'Payments' },
  { id: 'retention', title: 'Customer retention' },
];

export const DEFAULT_COMM_TEMPLATES: CommunicationTemplate[] = [
  {
    id: 'booking_confirmed',
    event_key: 'booking_confirmed',
    name: 'Booking confirmation',
    category: 'appointments',
    timing_label: 'When booking is created',
    send_delay_minutes: 0,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'confirmed',
    subject: 'Your North Splash detail is confirmed',
    body: 'Hello {customer_first_name},\n\nYour detail is confirmed.\n\n{appointment_time}\n{service}\n{vehicle}\n\nAssigned detailer: {detailer_name}\n{price}\n\nVIEW APPOINTMENT: {portal_link}',
    sms_body: 'North Splash: Your {service} is confirmed for {appointment_time}. View: {portal_link}',
  },
  {
    id: 'confirmation_request',
    event_key: 'booking_received',
    name: 'Confirmation request',
    category: 'appointments',
    timing_label: 'Immediately after booking',
    send_delay_minutes: 0,
    email_enabled: false,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'booked',
    subject: 'Please confirm your North Splash appointment',
    body: 'Hi {customer_first_name}, tap to confirm your {service} on {appointment_time}. {portal_link}',
    sms_body: 'North Splash: Please confirm your {service} on {appointment_time}. Confirm: {portal_link}',
  },
  {
    id: 'reminder_24h',
    event_key: 'appointment_reminder_24h',
    name: '24-hour reminder',
    category: 'appointments',
    timing_label: '24 hours before',
    send_delay_minutes: -1440,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'confirmed',
    subject: 'Tomorrow: your North Splash detail',
    body: 'Hi {customer_first_name},\n\nThis is a reminder that your {service} is tomorrow.\n{appointment_time}\n{vehicle}\n\nNeed to reschedule? {portal_link}',
    sms_body: 'North Splash: Reminder — {service} tomorrow at {appointment_time}. {portal_link}',
  },
  {
    id: 'reminder_2h',
    event_key: 'appointment_reminder_2h',
    name: '2-hour reminder',
    category: 'appointments',
    timing_label: '2 hours before',
    send_delay_minutes: -120,
    email_enabled: false,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'confirmed',
    subject: 'Your detailer is heading out soon',
    body: 'Hi {customer_first_name}, your {service} starts in about two hours. {detailer_name} is assigned. {portal_link}',
    sms_body: 'North Splash: Your {service} is in 2 hours. {detailer_name} is assigned. {portal_link}',
  },
  {
    id: 'detailer_assigned',
    event_key: 'detailer_assigned',
    name: 'Detailer assigned',
    category: 'field',
    timing_label: 'When a detailer is assigned',
    send_delay_minutes: 0,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'confirmed',
    subject: '{detailer_name} is assigned to your detail',
    body: 'Assigned Detailer\n{detailer_name}\n\n{service} · {vehicle}\n{appointment_time}\n{price}',
    sms_body: 'North Splash: {detailer_name} is assigned to your {service} on {appointment_time}.',
  },
  {
    id: 'detailer_en_route',
    event_key: 'detailer_en_route',
    name: 'Detailer en route',
    category: 'field',
    timing_label: 'Detailer taps En Route',
    send_delay_minutes: 0,
    email_enabled: false,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'en_route',
    subject: '{detailer_name} is on the way',
    body: 'Your detailer is on the way.\nETA {eta}\nTrack: {portal_link}',
    sms_body: 'North Splash: {detailer_name} is on the way to your {service}. ETA {eta}. Track: {portal_link}',
  },
  {
    id: 'detailer_approaching',
    event_key: 'detailer_approaching',
    name: 'ETA / arrival update',
    category: 'field',
    timing_label: 'Detailer approaching',
    send_delay_minutes: 0,
    email_enabled: false,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'en_route',
    subject: '{detailer_name} is almost there',
    body: 'ETA {eta}. Track your appointment: {portal_link}',
    sms_body: 'North Splash: {detailer_name} is approaching. ETA {eta}. {portal_link}',
  },
  {
    id: 'detailer_arrived',
    event_key: 'detailer_arrived',
    name: 'Detailer arrived',
    category: 'field',
    timing_label: 'Detailer taps Arrived',
    send_delay_minutes: 0,
    email_enabled: false,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'en_route',
    subject: '{detailer_name} has arrived',
    body: '{detailer_name} has arrived for your {service}.',
    sms_body: 'North Splash: {detailer_name} has arrived for your appointment.',
  },
  {
    id: 'job_started',
    event_key: 'job_started',
    name: 'Job started',
    category: 'field',
    timing_label: 'Job starts',
    send_delay_minutes: 0,
    email_enabled: false,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'in_progress',
    subject: 'Your detail is in progress',
    body: 'Your {service} is now in progress.',
    sms_body: 'North Splash: Your detail is now in progress.',
  },
  {
    id: 'job_completed',
    event_key: 'job_completed',
    name: 'Job completed',
    category: 'field',
    timing_label: 'Job completed',
    send_delay_minutes: 0,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Your vehicle is ready',
    body: 'Your {service} is complete.\nView photos & receipt: {portal_link}',
    sms_body: '✨ Your vehicle is ready. Your North Splash detail is complete. View photos & receipt: {portal_link}',
  },
  {
    id: 'invoice_sent',
    event_key: 'invoice_sent',
    name: 'Invoice sent',
    category: 'payments',
    timing_label: 'When payment is needed',
    send_delay_minutes: 0,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Invoice for your North Splash detail — {price}',
    body: 'Hi {customer_first_name}, your invoice for {service} is ready.\nAmount due: {price}\nPay now: {portal_link}',
    sms_body: 'North Splash: Your invoice for {service} is {price}. Pay: {portal_link}',
  },
  {
    id: 'payment_reminder',
    event_key: 'payment_reminder',
    name: 'Payment reminder',
    category: 'payments',
    timing_label: 'If unpaid',
    send_delay_minutes: 1440,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Reminder: {price} due for your detail',
    body: 'A friendly reminder that {price} is still due for your {service}. Pay: {portal_link}',
    sms_body: 'North Splash: {price} is still due for your {service}. Pay: {portal_link}',
  },
  {
    id: 'payment_received',
    event_key: 'payment_received',
    name: 'Payment received',
    category: 'payments',
    timing_label: 'When payment completes',
    send_delay_minutes: 0,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Receipt — North Splash Auto Luxe',
    body: 'Payment received. Thank you, {customer_first_name}.\n{service} · {vehicle}\n{price}\nReceipt: {portal_link}',
    sms_body: 'North Splash: Payment received for {service}. Receipt: {portal_link}',
  },
  {
    id: 'refund_issued',
    event_key: 'refund_issued',
    name: 'Refund issued',
    category: 'payments',
    timing_label: 'When a refund is issued',
    send_delay_minutes: 0,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Refund issued — North Splash',
    body: 'A refund of {price} has been issued for {service}.',
    sms_body: 'North Splash: A refund of {price} was issued for {service}.',
  },
  {
    id: 'thank_you',
    event_key: 'thank_you',
    name: 'Thank-you',
    category: 'retention',
    timing_label: 'Shortly after completion',
    send_delay_minutes: 60,
    email_enabled: true,
    sms_enabled: false,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Thank you for trusting North Splash',
    body: 'Thank you, {customer_first_name}. It was a pleasure detailing your {vehicle}. Photos: {portal_link}',
    sms_body: 'North Splash: Thank you for trusting us with your {vehicle}. Photos: {portal_link}',
  },
  {
    id: 'review_request',
    event_key: 'review_request',
    name: 'Review request',
    category: 'retention',
    timing_label: 'Shortly after completion',
    send_delay_minutes: 180,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'complete',
    subject: 'How was your North Splash detail?',
    body: 'If {detailer_name} took care of your {vehicle}, a short review helps other drivers find us. {portal_link}',
    sms_body: 'North Splash: How was your detail? Leave a quick review: {portal_link}',
  },
  {
    id: 'rebooking_30d',
    event_key: 'rebooking_30d',
    name: '30-day follow-up',
    category: 'retention',
    timing_label: '30 days after completion',
    send_delay_minutes: 43200,
    email_enabled: true,
    sms_enabled: false,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Your {vehicle} is due for a refresh',
    body: 'It has been about a month since your {service}. Book the next visit: {portal_link}',
    sms_body: 'North Splash: It’s been a month since your last detail. Book again: {portal_link}',
  },
  {
    id: 'rebooking_90d',
    event_key: 'rebooking_90d',
    name: '90-day rebooking reminder',
    category: 'retention',
    timing_label: '90 days after completion',
    send_delay_minutes: 129600,
    email_enabled: true,
    sms_enabled: true,
    is_enabled: true,
    status_step: 'complete',
    subject: 'Time for your next detail?',
    body: 'Time for your next detail, {customer_first_name}. Your {vehicle} is due for another North Splash visit. {portal_link}',
    sms_body: 'North Splash: Time for your next detail? Book your {vehicle}: {portal_link}',
  },
];

export const SAMPLE_VARS: Record<string, string> = {
  customer_first_name: 'Matthew',
  detailer_name: 'Marcus',
  vehicle: '2022 BMW 330i',
  service: 'Luxe Signature Detail',
  appointment_time: 'Saturday, September 12 · 10:30 AM',
  price: '$275.00',
  eta: '10:42 AM',
  portal_link: 'northsplash.com/appointment',
};

export function fillTemplate(text: string, vars: Record<string, string> = SAMPLE_VARS) {
  return String(text || '').replace(/\{([a-z_]+)\}/gi, (_, key: string) => vars[key] ?? `{${key}}`);
}

export function channelLabel(t: Pick<CommunicationTemplate, 'email_enabled' | 'sms_enabled'>) {
  if (t.email_enabled && t.sms_enabled) return 'Email + SMS';
  if (t.email_enabled) return 'Email';
  if (t.sms_enabled) return 'SMS';
  return 'Off';
}
