export const WORKSPACE_REFS: Record<
  string,
  { modeled: string; title: string; lead: string; kicker: string }
> = {
  command_center: {
    kicker: 'Owner',
    title: 'Home',
    modeled: 'Stripe Dashboard',
    lead: 'Balances, today’s work, and the next action.',
  },
  dashboard: {
    kicker: 'Owner',
    title: 'Overview',
    modeled: 'Stripe Dashboard',
    lead: 'Gross volume, payouts, and live counts. Open a row to drill in.',
  },
  leads: {
    kicker: 'Field sales',
    title: 'Leads',
    modeled: 'SalesRabbit + HubSpot + SPOTIO',
    lead: 'Pins, knocks, pipeline, and the next door — without leaving the board.',
  },
  crm: {
    kicker: 'CRM',
    title: 'Pipeline',
    modeled: 'HubSpot',
    lead: 'Deals move left to right. Search, filter, and convert without leaving the board.',
  },
  employees: {
    kicker: 'People',
    title: 'Team',
    modeled: 'Rippling + Gusto',
    lead: 'Directory, pay, and onboarding in one profile.',
  },
  team: {
    kicker: 'People',
    title: 'Team',
    modeled: 'Rippling + Gusto',
    lead: 'Directory, pay, and onboarding in one profile.',
  },
  customers: {
    kicker: 'CRM',
    title: 'Customers',
    modeled: 'HubSpot',
    lead: 'Search the company, last job, and spend. Click a row for the record.',
  },
  client_photos: {
    kicker: 'CRM',
    title: 'Client photos',
    modeled: 'Jobber + Housecall Pro',
    lead: 'Import before and after shots onto a client. Star portfolio work you can show.',
  },
  calendar: {
    kicker: 'Schedule',
    title: 'Calendar',
    modeled: 'Jobber',
    lead: 'Week-first schedule with a day strip. Drag or tap a slot to book.',
  },
  schedule: {
    kicker: 'Schedule',
    title: 'Calendar',
    modeled: 'Jobber',
    lead: 'Week-first schedule with a day strip. Drag or tap a slot to book.',
  },
  availability: {
    kicker: 'Schedule',
    title: 'Availability',
    modeled: 'Jobber',
    lead: 'Open hours the calendar can book into. Block days when you are closed.',
  },
  staff_schedule: {
    kicker: 'Labor',
    title: 'Staff schedule',
    modeled: 'Deputy',
    lead: 'Who is on, where, and when. Publish the week.',
  },
  appointments: {
    kicker: 'Jobs',
    title: 'Appointments',
    modeled: 'Jobber',
    lead: 'Upcoming visits with customer, address, and stage.',
  },
  archived: {
    kicker: 'Jobs',
    title: 'Archived jobs',
    modeled: 'Jobber',
    lead: 'Cleared visits stay searchable. Restore or keep them off the live board.',
  },
  dispatch: {
    kicker: 'Ops',
    title: 'Dispatch',
    modeled: 'ServiceTitan',
    lead: 'Techs as columns, jobs as cards, live status on every board cell.',
  },
  job_assignments: {
    kicker: 'Ops',
    title: 'Job assignment',
    modeled: 'ServiceTitan',
    lead: 'Assign the tech, the manager, and the originating rep from one board.',
  },
  jobs: {
    kicker: 'Detailing',
    title: 'Job workflow',
    modeled: 'Housecall Pro + Uber',
    lead: 'Inspection, photos, checklist, and live status: booked → en route → on site → done.',
  },
  d2d: {
    kicker: 'Field',
    title: 'Door to door',
    modeled: 'SalesRabbit',
    lead: 'Map, pins, knock colors, and the next door. This is the core field product.',
  },
  sales: {
    kicker: 'Field',
    title: 'Door to door',
    modeled: 'SalesRabbit',
    lead: 'Doors, conversion, and revenue by rep.',
  },
  territories: {
    kicker: 'Field',
    title: 'Territories',
    modeled: 'SalesRabbit',
    lead: 'Draw the neighborhood, assign a rep, then work every door inside the pin.',
  },
  messages: {
    kicker: 'Chat',
    title: 'Messages',
    modeled: 'Microsoft Teams',
    lead: 'Company channel, DMs, and teams. Send stays on screen until it lands.',
  },
  payments: {
    kicker: 'Money',
    title: 'Payments',
    modeled: 'Square',
    lead: 'Invoices, deposits, and payouts — not a generic ledger.',
  },
  finance: {
    kicker: 'Money',
    title: 'Finance & payroll',
    modeled: 'Gusto + Stripe',
    lead: 'Labor cost, expenses, and operating profit. Estimates for operators, not a tax filing.',
  },
  reports: {
    kicker: 'Finance',
    title: 'Reports',
    modeled: 'Stripe',
    lead: 'Gross volume, by product, by closer. Export when you need the CSV.',
  },
  permissions: {
    kicker: 'Admin',
    title: 'Permissions',
    modeled: 'Stripe',
    lead: 'Roles and what each one can see. Change access here, not in a spreadsheet.',
  },
  recruiting: {
    kicker: 'People',
    title: 'Hiring',
    modeled: 'Gusto + ADP',
    lead: 'Pipeline → offer → onboarding packet. Convert puts the hire on Team.',
  },
  communications: {
    kicker: 'Customer',
    title: 'Communications',
    modeled: 'Housecall Pro + Jobber',
    lead: 'Job updates, reminders, and follow-ups the customer actually reads.',
  },
  settings: {
    kicker: 'Admin',
    title: 'Settings',
    modeled: 'Stripe',
    lead: 'Business, catalog, and integrations. Search the page, then save.',
  },
  pay_settings: {
    kicker: 'People',
    title: 'Pay structure',
    modeled: 'Gusto + Rippling',
    lead: 'Hourly, salary, commission, per-job, or mixed — set once, payroll reads it.',
  },
  training: {
    kicker: 'Academy',
    title: 'Training',
    modeled: 'Gusto onboarding + SalesRabbit playbooks',
    lead: 'Door scripts and detailing standards new hires finish before they go live.',
  },
  timeclock: {
    kicker: 'Labor',
    title: 'Time clock',
    modeled: 'Deputy',
    lead: 'Clock in, breaks, and timesheets for every shift.',
  },
  time_off: {
    kicker: 'Labor',
    title: 'Time off',
    modeled: 'Deputy + Gusto',
    lead: 'Request, approve, and keep coverage visible on the week board.',
  },
  payroll_approval: {
    kicker: 'People',
    title: 'Timesheets',
    modeled: 'Gusto',
    lead: 'Review hours, approve the card, then close the pay period.',
  },
  crews: {
    kicker: 'Ops',
    title: 'Crews',
    modeled: 'ServiceTitan',
    lead: 'Who is on which crew, live activity, and the daily closeout.',
  },
  fleet: {
    kicker: 'CRM',
    title: 'Fleet accounts',
    modeled: 'HubSpot',
    lead: 'Company accounts, vehicles, and repeat work in one record.',
  },
  locations: {
    kicker: 'Admin',
    title: 'Locations',
    modeled: 'Stripe',
    lead: 'Service areas and shop sites the calendar and dispatch read from.',
  },
  marketing: {
    kicker: 'Growth',
    title: 'Marketing',
    modeled: 'HubSpot',
    lead: 'Campaigns and follow-up sequences tied to the same customer record.',
  },
  automations: {
    kicker: 'Admin',
    title: 'Automations',
    modeled: 'HubSpot + Jobber',
    lead: 'When this happens, do that — reminders, reviews, and inactive-rep alerts.',
  },
  approvals: {
    kicker: 'Ops',
    title: 'Approvals',
    modeled: 'Rippling',
    lead: 'Time off, expenses, and exceptions waiting on a manager.',
  },
  incidents: {
    kicker: 'Ops',
    title: 'Incidents',
    modeled: 'ServiceTitan',
    lead: 'Damage, complaints, and rework — log it, assign it, close it.',
  },
  purchasing: {
    kicker: 'Ops',
    title: 'Purchasing',
    modeled: 'ServiceTitan',
    lead: 'Chemicals, parts, and vendor orders against inventory levels.',
  },
  inventory: {
    kicker: 'Ops',
    title: 'Inventory',
    modeled: 'ServiceTitan',
    lead: 'On-hand counts, reorder points, and what is on the truck.',
  },
  equipment: {
    kicker: 'Ops',
    title: 'Equipment',
    modeled: 'ServiceTitan',
    lead: 'Washers, extractors, and vehicles assigned to a tech.',
  },
  tasks: {
    kicker: 'Ops',
    title: 'Tasks',
    modeled: 'Jobber',
    lead: 'Internal work that is not a customer job. Assign it and due it.',
  },
  documents: {
    kicker: 'People',
    title: 'Documents',
    modeled: 'Rippling + Gusto',
    lead: 'I-9, training files, and write-ups on the employee record.',
  },
  notifications: {
    kicker: 'Chat',
    title: 'Notifications',
    modeled: 'Microsoft Teams',
    lead: 'Announcements to a person or a portal group.',
  },
  audit: {
    kicker: 'Admin',
    title: 'Audit log',
    modeled: 'Stripe',
    lead: 'Who changed access, pay, or a job — and when.',
  },
  visitors: {
    kicker: 'Growth',
    title: 'Site visitors',
    modeled: 'Stripe',
    lead: 'Sessions, pages, and sources — traffic as an operator metric.',
  },
  retention: {
    kicker: 'CRM',
    title: 'Retention',
    modeled: 'HubSpot + Housecall Pro',
    lead: 'Who is due back, memberships, and review requests.',
  },
  continuity: {
    kicker: 'Admin',
    title: 'Backups',
    modeled: 'Stripe',
    lead: 'Exports and restore points for the live company record.',
  },
  owner_growth: {
    kicker: 'Owner',
    title: 'Growth planner',
    modeled: 'Stripe',
    lead: 'Targets, capacity, and the next hire — owner math, not a pitch deck.',
  },
  owner_profits: {
    kicker: 'Owner',
    title: 'Profit tracker',
    modeled: 'Stripe',
    lead: 'Collected vs. labor vs. expenses.',
  },
  payment_test: {
    kicker: 'Money',
    title: 'Payment test',
    modeled: 'Square',
    lead: 'Send a one-cent charge to prove the reader and payout path.',
  },
}

export function workspaceRef(id: string) {
  return (
    WORKSPACE_REFS[id] || {
      kicker: 'Workspace',
      title: id.replace(/_/g, ' '),
      modeled: 'NS Auto Luxe',
      lead: 'Live company data.',
    }
  )
}
