import EmployeeAvatar from '@/components/EmployeeAvatar';
import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, Clock3, UserCheck } from 'lucide-react';
import type { Appointment, Employee } from '@/lib/supabase';
import SharedCalendar from '@/components/SharedCalendar';
import { dayKey, timeLabel } from '@/lib/scheduling';
import { money } from '@/lib/data';

type Props={employees:Employee[];appointments:Appointment[];focusEmployeeId?:string;onCreate:(p:Record<string,unknown>)=>Promise<void>|void;onUpdate:(id:string,p:Record<string,unknown>)=>Promise<void>|void};
export default function AdminTeamCalendar({employees,appointments,focusEmployeeId,onCreate,onUpdate}:Props){
 const activeTeam=employees.filter(e=>['detailer','d2d_agent','manager'].includes(e.role)&&e.status!=='inactive'); const [employeeId,setEmployeeId]=useState(activeTeam[0]?.id||''); useEffect(()=>{if(focusEmployeeId&&activeTeam.some(e=>e.id===focusEmployeeId))setEmployeeId(focusEmployeeId)},[focusEmployeeId]); const employee=activeTeam.find(e=>e.id===employeeId); const today=dayKey(new Date());
 const counts=useMemo(()=>Object.fromEntries(activeTeam.map(e=>[e.id,appointments.filter(a=>a.assigned_employee_id===e.id&&a.scheduled_at&&dayKey(a.scheduled_at)===today&&!['cancelled'].includes(a.status)).length])),[activeTeam,appointments,today]);
 return <div className="admin-team-calendar-v15"><div className="team-calendar-layout"><aside className="team-calendar-people"><div className="team-calendar-side-head"><span className="eyebrow">TEAM SCHEDULES</span><h3>Employees</h3><p>Click a name to open their current calendar.</p></div>{activeTeam.map(e=>{const next=appointments.filter(a=>a.assigned_employee_id===e.id&&a.scheduled_at&&new Date(a.scheduled_at)>=new Date()&&!['cancelled'].includes(a.status)).sort((a,b)=>new Date(a.scheduled_at!).getTime()-new Date(b.scheduled_at!).getTime())[0];return <button key={e.id} className={e.id===employeeId?'active':''} onClick={()=>setEmployeeId(e.id)}><EmployeeAvatar employee={e} size="md" className="emp-calendar-avatar"/><div><strong>{e.name}</strong><span>{e.title||e.role.replaceAll('_',' ')}</span><small>{counts[e.id]||0} today{next?` · next ${timeLabel(next.scheduled_at!)}`:''}</small></div><ChevronRight/></button>})}</aside><section className="team-calendar-main">{employee?<><div className="employee-calendar-banner"><div><UserCheck/><span>Viewing</span><strong>{employee.name}</strong><small>{employee.title||employee.role} · {counts[employee.id]||0} scheduled today</small></div><div><CalendarDays/><span>Scheduled revenue</span><strong>{money(appointments.filter(a=>a.assigned_employee_id===employee.id&&a.scheduled_at&&dayKey(a.scheduled_at)===today).reduce((n,a)=>n+Number(a.price||0),0))}</strong><small>today</small></div><div><Clock3/><span>Capacity</span><strong>{appointments.filter(a=>a.assigned_employee_id===employee.id&&a.scheduled_at&&dayKey(a.scheduled_at)===today).reduce((n,a)=>n+Number(a.estimated_duration_minutes||120),0)/60} hrs</strong><small>scheduled today</small></div></div><SharedCalendar mode="admin" appointments={appointments} employees={employees} employeeId={employee.id} title={`${employee.name}'s Calendar`} onCreate={onCreate} onUpdate={onUpdate}/></>:<div className="ns-empty">Add an employee to open a team calendar.</div>}</section></div></div>
}
