import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Camera, CheckCircle2, Clock3, MapPin, MessageSquare, Navigation, Play, Route, ShieldCheck, Sparkles } from 'lucide-react';
import type { Appointment, Employee } from '@/lib/supabase';
import { supabase } from '@/lib/supabase';
import { money } from '@/lib/data';
import { dayKey, JOB_STATUS_LABELS, routeAppointments, timeLabel } from '@/lib/scheduling';
import JobWorkflow from '@/components/JobWorkflow';

type Props={appointments:Appointment[];employee?:Employee|null;onUpdate:(id:string,payload:Record<string,unknown>)=>Promise<void>|void};
function osmEmbed(a:Appointment){const lat=Number(a.latitude||0),lng=Number(a.longitude||0);if(!lat||!lng)return '';const d=.008;return `https://www.openstreetmap.org/export/embed.html?bbox=${lng-d}%2C${lat-d}%2C${lng+d}%2C${lat+d}&layer=mapnik&marker=${lat}%2C${lng}`}
function externalNav(a:Appointment){const dest=a.latitude&&a.longitude?`${a.latitude},${a.longitude}`:encodeURIComponent(a.service_address||'');return `https://www.google.com/maps/dir/?api=1&destination=${dest}`}
function statusLabel(a:Appointment){return JOB_STATUS_LABELS[a.field_status||a.status]||String(a.field_status||a.status).replaceAll('_',' ')}

export default function DetailerRouteCenter({appointments,employee,onUpdate}:Props){
  const today=dayKey(new Date());
  const jobs=useMemo(()=>routeAppointments(appointments).filter(a=>a.scheduled_at&&dayKey(a.scheduled_at)===today),[appointments,today]);
  const [selected,setSelected]=useState<string|null>(jobs[0]?.id||null);const [jobMode,setJobMode]=useState(false);const [issueOpen,setIssueOpen]=useState(false);const [issue,setIssue]=useState({incident_type:'customer_access',severity:'normal',description:''});const [note,setNote]=useState('');const [activity,setActivity]=useState<any[]>([]);
  useEffect(()=>{if(!selected&&jobs[0])setSelected(jobs[0].id)},[jobs,selected]);
  const active=jobs.find(j=>j.id===selected)||jobs[0]||null;
  useEffect(()=>{if(!active)return;supabase.from('appointment_activity').select('*').eq('appointment_id',active.id).order('created_at',{ascending:false}).limit(12).then(r=>setActivity(r.data??[]))},[active?.id]);
  const action=async(a:Appointment,status:string)=>{const now=new Date().toISOString();const payload:Record<string,unknown>={field_status:status,dispatch_status:status};if(status==='en_route')payload.en_route_at=now;if(status==='arrived')payload.arrived_at=now;if(status==='in_progress'){payload.started_at=now;payload.status='in_progress'}if(status==='completed'){payload.finished_at=now;payload.completed_at=now;payload.status='completed'}await onUpdate(a.id,payload)};
  const saveIssue=async(e:React.FormEvent)=>{e.preventDefault();if(!active||!issue.description.trim())return;const {error}=await supabase.from('incident_reports').insert({appointment_id:active.id,employee_id:employee?.id||null,...issue});if(error)return alert(error.message);await supabase.from('appointment_activity').insert({appointment_id:active.id,actor_employee_id:employee?.id||null,event_type:'issue_reported',details:{type:issue.incident_type,severity:issue.severity,description:issue.description}});setIssue({incident_type:'customer_access',severity:'normal',description:''});setIssueOpen(false);alert('Issue sent to operations.')};
  const addNote=async()=>{if(!active||!note.trim())return;const {error}=await supabase.from('appointment_activity').insert({appointment_id:active.id,actor_employee_id:employee?.id||null,event_type:'internal_note',details:{note:note.trim()}});if(error)return alert(error.message);setActivity(p=>[{id:crypto.randomUUID(),event_type:'internal_note',details:{note:note.trim()},created_at:new Date().toISOString()},...p]);setNote('')};
  const nextJob=active?jobs[jobs.indexOf(active)+1]:null;
  const done=jobs.filter(j=>j.status==='completed'||j.field_status==='finished').length;
  return <div className="detailer-route-v16">
    <div className="route-center-head v16"><div><span className="eyebrow">TODAY'S MOBILE ROUTE</span><h2>Detailer Route Center</h2><p>Navigate, service, document and close every appointment from one mobile-first workspace.</p></div><div className="route-summary v16"><div><strong>{jobs.length}</strong><span>stops</span></div><div><strong>{done}/{jobs.length}</strong><span>completed</span></div><div><b>{money(jobs.reduce((n,a)=>n+Number(a.price||0),0))}</b><span>scheduled value</span></div></div></div>
    {!jobs.length?<div className="ns-empty">No jobs are assigned to you today.</div>:<div className="detailer-route-layout v16"><aside className="detailer-stop-list v16"><div className="route-progress"><span>Today's route progress</span><strong>{jobs.length?Math.round(done/jobs.length*100):0}%</strong><i><b style={{width:`${jobs.length?done/jobs.length*100:0}%`}}/></i></div>{jobs.map((a,i)=><button key={a.id} className={`${a.id===active?.id?'active ':''}${a.status==='completed'?'done':''}`} onClick={()=>{setSelected(a.id);setJobMode(false)}}><span className="stop-number">{a.status==='completed'?<CheckCircle2 size={16}/>:i+1}</span><div><strong>{timeLabel(a.scheduled_at!)} · {a.customer_name||'Customer'}</strong><span>{a.service_address||'Address pending'}</span><small>{a.service_name} · {statusLabel(a)}</small></div></button>)}</aside>{active&&<section className="detailer-route-main v16">
      <div className="detailer-map-shell v16">{osmEmbed(active)?<iframe title="Appointment map" src={osmEmbed(active)} loading="lazy"/>:<div className="detailer-map-placeholder"><MapPin size={34}/><strong>Map location pending</strong><span>The address still works with external navigation.</span></div>}<div className="detailer-map-overlay v16"><Route size={18}/><div><strong>Stop {jobs.indexOf(active)+1} of {jobs.length}</strong><span>{active.service_address||'Address pending'}</span></div><a href={externalNav(active)} target="_blank" rel="noreferrer"><Navigation size={16}/> Navigate</a></div></div>
      {!jobMode?<div className="detailer-job-card v16"><div className="detailer-job-title"><div><span className="eyebrow">CURRENT APPOINTMENT</span><h3>{active.customer_name||'Customer'} · {active.vehicle_info||'Vehicle not listed'}</h3><p>{active.service_name}{active.package_name?` · ${active.package_name}`:''}</p></div><strong>{money(active.price)}</strong></div><div className="detailer-job-meta"><span><Clock3/> {timeLabel(active.scheduled_at!)} · {active.estimated_duration_minutes||120} min</span><span><MapPin/> {active.service_address||'Address pending'}</span><span><ShieldCheck/> {active.payment_status?.replaceAll('_',' ')||'unpaid'} · {active.before_photos_required===false?'photos optional':'photos required'}</span></div>{active.notes&&<div className="detailer-note"><strong>Customer / job notes</strong><p>{active.notes}</p></div>}
        <div className="detailer-status-flow v16"><button onClick={()=>action(active,'en_route')} className={active.field_status==='en_route'?'active':''}><Navigation/>En Route</button><button onClick={()=>action(active,'arrived')} className={active.field_status==='arrived'?'active':''}><MapPin/>Arrived</button><button onClick={()=>action(active,'in_progress')} className={active.status==='in_progress'?'active':''}><Play/>Start Job</button><button onClick={()=>action(active,'completed')} className={active.status==='completed'?'active':''}><CheckCircle2/>Complete</button></div>
        <button className="detailer-enter-jobmode" onClick={()=>setJobMode(true)}><Sparkles/><div><strong>Open Full Job Mode</strong><span>Inspection · photos · checklist · signature · completion</span></div><span>→</span></button>
        <div className="detailer-ops-grid"><section><header><MessageSquare/><strong>Internal job note</strong></header><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Update admin/detailer team…"/><button onClick={addNote}>Add note</button></section><section><header><AlertTriangle/><strong>Need help?</strong></header><p>Report access, weather, customer, equipment or damage issues directly to operations.</p><button onClick={()=>setIssueOpen(true)}>Report issue</button></section></div>
        {activity.length>0&&<div className="detailer-activity"><strong>Recent activity</strong>{activity.slice(0,5).map(a=><div key={a.id}><i/><span>{String(a.event_type).replaceAll('_',' ')}</span><small>{a.details?.note||a.details?.description||new Date(a.created_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>)}</div>}
        {nextJob&&<div className="detailer-next-job"><Route/><div><span>Up next</span><strong>{timeLabel(nextJob.scheduled_at!)} · {nextJob.customer_name||nextJob.service_name}</strong><small>{nextJob.service_address}</small></div></div>}
      </div>:employee?<JobWorkflow appointment={active} employee={employee} onUpdate={job=>onUpdate(job.id,{field_status:job.field_status,status:job.status,started_at:job.started_at,finished_at:job.finished_at,completed_at:job.completed_at,qc_status:job.qc_status,customer_signature_at:job.customer_signature_at})} onClose={()=>setJobMode(false)}/>:<div className="ns-empty">Employee profile is required for full Job Mode.</div>}
    </section>}</div>}
    {issueOpen&&active&&<div className="detailer-issue-backdrop" onClick={()=>setIssueOpen(false)}><form className="detailer-issue-modal" onSubmit={saveIssue} onClick={e=>e.stopPropagation()}><span className="eyebrow">OPERATIONS SUPPORT</span><h3>Report an issue</h3><label>Issue type<select value={issue.incident_type} onChange={e=>setIssue(p=>({...p,incident_type:e.target.value}))}><option value="customer_access">Can't access property</option><option value="customer_no_show">Customer unavailable</option><option value="weather">Weather</option><option value="equipment">Equipment problem</option><option value="vehicle_damage">Vehicle / damage concern</option><option value="scope_change">Extra work / scope change</option><option value="other">Other</option></select></label><label>Severity<select value={issue.severity} onChange={e=>setIssue(p=>({...p,severity:e.target.value}))}><option value="normal">Normal</option><option value="urgent">Urgent</option><option value="critical">Critical</option></select></label><label>Details<textarea required rows={5} value={issue.description} onChange={e=>setIssue(p=>({...p,description:e.target.value}))}/></label><div><button type="button" className="btn-outline" onClick={()=>setIssueOpen(false)}>Cancel</button><button className="btn-primary">Send to Operations</button></div></form></div>}
  </div>
}
