import { useEffect, useMemo, useState } from 'react';
import { Activity, BriefcaseBusiness, Calendar, ClipboardCheck, Clock3, Mail, MessageCircle, Phone, Save, Trash2, WalletCards, X } from 'lucide-react';
import EmployeeAvatar from './EmployeeAvatar';
import EmployeeOnboardingTab from './EmployeeOnboardingTab';
import CompensationRuleBuilder from './CompensationRuleBuilder';
import { compensationSummary } from '@/lib/compensation';
import { SYSTEM_ROLES } from '@/lib/rolePresets';
import { supabase, type Appointment, type Employee } from '@/lib/supabase';
import { money, prettyLabel } from '@/lib/data';

type Tab='onboarding'|'overview'|'employment'|'pay'|'documents'|'schedule'|'activity';
type Props={employee:Employee;employees:Employee[];appointments:Appointment[];initialTab?:Tab;onClose:()=>void;onOpenCalendar:(id:string)=>void;onOpenMessages:()=>void;onDelete:(id:string)=>void;onUpdated:(e:Employee)=>void};

const payLabel=(e:Employee)=>compensationSummary(e);

export default function EmployeeProfileDrawer({employee:e,employees,appointments,initialTab,onClose,onOpenCalendar,onOpenMessages,onDelete,onUpdated}:Props){
 const needsOnboarding=e.onboarding_status && e.onboarding_status!=='complete';
 const [tab,setTab]=useState<Tab>(initialTab||(needsOnboarding?'onboarding':'overview'));const [draft,setDraft]=useState<Partial<Employee>>({...e});const [saving,setSaving]=useState(false);
 useEffect(()=>{setDraft({...e})},[e.id]);
 useEffect(()=>{if(initialTab)setTab(initialTab)},[initialTab,e.id]);
 const assigned=useMemo(()=>appointments.filter(a=>a.assigned_employee_id===e.id&&!a.archived),[appointments,e.id]);
 const upcoming=assigned.filter(a=>a.scheduled_at&&new Date(a.scheduled_at)>=new Date()&&!['cancelled','completed'].includes(a.status)).sort((a,b)=>+new Date(a.scheduled_at!)-+new Date(b.scheduled_at!));
 const completed=assigned.filter(a=>a.status==='completed');
 const save=async()=>{const name=String(draft.name||'').trim();if(!name)return alert('Name is required.');setSaving(true);const payload={name,email:String(draft.email||'').trim()||null,phone:String(draft.phone||'').trim()||null,role:draft.role||e.role,employment_level:Number(draft.employment_level||1),title:draft.title||null,department:draft.department||null,status:draft.status||'active',manager_employee_id:draft.manager_employee_id||null,work_location:draft.work_location||null,hire_date:draft.hire_date||null,pay_type:draft.pay_type||'hourly',hourly_rate:Number(draft.hourly_rate||0),weekly_base:Number(draft.weekly_base||0),commission_rate:Number(draft.commission_rate||0),annual_salary:Number(draft.annual_salary||0),per_job_rate:Number(draft.per_job_rate||0),flat_commission:Number(draft.flat_commission||0),commission_basis:draft.commission_basis||'revenue',pay_schedule:draft.pay_schedule||'weekly',overtime_eligible:draft.overtime_eligible!==false,compensation_notes:draft.compensation_notes||null,custom_compensation:draft.custom_compensation||{rules:[]},work_modes:Array.isArray(draft.work_modes)?draft.work_modes:[]};const{data,error}=await supabase.from('employees').update(payload).eq('id',e.id).select().single();setSaving(false);if(error)return alert(error.message);if(data){setDraft(data);onUpdated(data)}};
 const field=(label:string,key:keyof Employee,placeholder='')=><label className="profile-field-v25"><span>{label}</span><input value={String(draft[key]??'')} placeholder={placeholder} onChange={ev=>setDraft(p=>({...p,[key]:ev.target.value}))}/></label>;
 return <div className="team-profile-backdrop" onClick={onClose}><section className="team-profile-drawer employee-profile-v25" onClick={ev=>ev.stopPropagation()}>
  <header className="employee-profile-hero-v25"><div className="team-profile-identity"><EmployeeAvatar employee={e} size="xl" editable onUploaded={url=>onUpdated({...e,avatar_url:url})}/><div><span className="eyebrow">{e.title||prettyLabel(e.role)}</span><h2>{e.name}</h2><p>{e.department||'North Splash Auto Luxe'} · {e.status||'active'}</p></div></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></header>
  <nav className="employee-profile-tabs-v25">{([['onboarding','Onboarding'],['overview','Overview'],['employment','Employment'],['pay','Pay'],['documents','Documents'],['schedule','Schedule'],['activity','Activity']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}{id==='onboarding'&&needsOnboarding?' ·':''}</button>)}</nav>
  <div className="employee-profile-body-v25">
   {tab==='onboarding'&&<EmployeeOnboardingTab employee={e} onUpdated={onUpdated}/>}
   {tab==='overview'&&<><div className="team-profile-kpis"><div><strong>{completed.length}</strong><span>Completed jobs</span></div><div><strong>{upcoming.length}</strong><span>Upcoming jobs</span></div><div><strong>{e.onboarding_status==='complete'?'Complete':e.onboarding_status==='in_progress'?'Packet open':e.status||'active'}</strong><span>{e.onboarding_status&&e.onboarding_status!=='complete'?'Onboarding':'Status'}</span></div><div><strong>{payLabel(e)}</strong><span>Pay structure</span></div></div><div className="team-profile-info"><div><small>Email</small><strong>{e.email||'Not added'}</strong></div><div><small>Phone</small><strong>{e.phone||'Not added'}</strong></div><div><small>Job title</small><strong>{e.title||prettyLabel(e.role)}</strong></div><div><small>Department</small><strong>{e.department||'Not assigned'}</strong></div><div><small>Manager</small><strong>{employees.find(m=>m.id===e.manager_employee_id)?.name||'Not assigned'}</strong></div><div><small>Training</small><strong>{e.training_status||'Active'}</strong></div></div></>}
   {tab==='employment'&&<section className="profile-edit-grid-v25"><div className="profile-section-title-v25"><BriefcaseBusiness/><div><strong>Employment</strong><small>Name, role, and reporting stay editable after hire — fix a misspelled name or move someone without deleting them.</small></div></div>{field('Full name','name','Full name')}{field('Email','email','team@northsplash.com')}{field('Phone','phone','330-000-0000')}<label className="profile-field-v25"><span>System role</span><select value={String(draft.role||e.role)} onChange={ev=>setDraft(p=>({...p,role:ev.target.value}))}>{!SYSTEM_ROLES.some(r=>r.value===String(draft.role||e.role))&&<option value={String(draft.role||e.role)}>{prettyLabel(String(draft.role||e.role))}</option>}{SYSTEM_ROLES.map(r=><option value={r.value} key={r.value}>{r.label}</option>)}</select></label><label className="profile-field-v25"><span>Employee level</span><select value={String(draft.employment_level||1)} onChange={ev=>setDraft(p=>({...p,employment_level:Number(ev.target.value)}))}>{[1,2,3,4,5].map(n=><option value={n} key={n}>Level {n}</option>)}</select></label>{field('Custom Job Title','title','Detailing Operations Manager')}{field('Department','department','Operations')}<label className="profile-field-v25"><span>Status</span><select value={String(draft.status||'active')} onChange={ev=>setDraft(p=>({...p,status:ev.target.value}))}><option value="active">Active</option><option value="inactive">Inactive</option><option value="leave">On Leave</option></select></label><label className="profile-field-v25"><span>Manager</span><select value={String(draft.manager_employee_id||'')} onChange={ev=>setDraft(p=>({...p,manager_employee_id:ev.target.value||null}))}><option value="">No manager</option>{employees.filter(x=>x.id!==e.id&&['manager','admin'].includes(x.role)).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label>{field('Work Location','work_location','Raleigh')}{field('Hire Date','hire_date')}<div className="profile-field-v25 wide capability-field-v27"><span>Work Modes / Capabilities</span><div className="capability-checks-v27">{([['d2d','D2D sales / canvassing'],['detailer','Detailing / field service'],['manager','Manager tools']] as const).map(([value,label])=><label key={value}><input type="checkbox" checked={(Array.isArray(draft.work_modes)?draft.work_modes:[]).includes(value)} onChange={ev=>setDraft(prev=>{const current=Array.isArray(prev.work_modes)?prev.work_modes:[];return {...prev,work_modes:ev.target.checked?[...new Set([...current,value])]:current.filter(x=>x!==value)}})}/><span>{label}</span></label>)}</div><small>Use this for owners, hybrid employees, or anyone who works across multiple job functions.</small></div></section>}
   {tab==='documents'&&<section className="profile-edit-grid-v25"><div className="profile-section-title-v25"><ClipboardCheck/><div><strong>Documents</strong><small>I-9, W-4, handbook, certifications, and signed offer letters. Complete the Onboarding tab for last-four tax and deposit.</small></div></div><div className="ns-empty compact">No files attached yet. The hire packet (headshot, legal name, tax last-4, deposit last-4, I-9) is on the Onboarding tab.</div><button type="button" className="btn-outline" onClick={()=>setTab('onboarding')}>Open onboarding packet</button></section>}
   {tab==='pay'&&<section className="profile-edit-grid-v25"><div className="profile-section-title-v25"><WalletCards/><div><strong>Compensation</strong><small>Individual pay overrides role presets. Mix salary, hourly, and commission for admins and field staff.</small></div></div><label className="profile-field-v25"><span>Pay Structure</span><select value={String(draft.pay_type||'hourly')} onChange={ev=>setDraft(p=>({...p,pay_type:ev.target.value}))}><option value="hourly">Hourly</option><option value="salary">Salary</option><option value="base_commission">Base + Commission</option><option value="commission_only">Commission Only</option><option value="per_job">Per Job</option><option value="hourly_plus_commission">Hourly + Commission</option><option value="salary_plus_commission">Salary + Commission</option><option value="custom">Custom / Mixed</option></select></label><label className="profile-field-v25"><span>Pay Schedule</span><select value={String(draft.pay_schedule||'weekly')} onChange={ev=>setDraft(p=>({...p,pay_schedule:ev.target.value}))}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option><option value="semimonthly">Twice Monthly</option><option value="monthly">Monthly</option></select></label>{['hourly','hourly_plus_commission','custom'].includes(String(draft.pay_type||''))&&field('Hourly Rate','hourly_rate')}{['salary','salary_plus_commission','custom'].includes(String(draft.pay_type||''))&&field('Annual Salary','annual_salary')}{['base_commission','custom'].includes(String(draft.pay_type||''))&&field('Weekly Base','weekly_base')}{['base_commission','commission_only','hourly_plus_commission','salary_plus_commission','custom'].includes(String(draft.pay_type||''))&&field('Commission %','commission_rate')}{['commission_only','custom'].includes(String(draft.pay_type||''))&&field('Flat Commission / Sale','flat_commission')}{['per_job','custom'].includes(String(draft.pay_type||''))&&field('Per-Job Rate','per_job_rate')}<div className="profile-field-v25 wide compensation-builder-wrap-v27"><CompensationRuleBuilder value={draft.custom_compensation} onChange={custom_compensation=>setDraft(p=>({...p,custom_compensation}))}/></div><label className="profile-field-v25 wide"><span>Compensation Notes</span><textarea rows={4} value={String(draft.compensation_notes||'')} onChange={ev=>setDraft(p=>({...p,compensation_notes:ev.target.value}))}/></label></section>}
   {tab==='schedule'&&<section className="team-profile-schedule"><div className="admin-card-header"><h3><Calendar size={16}/>Upcoming Calendar</h3><button className="btn-outline btn-sm" onClick={()=>onOpenCalendar(e.id)}>Open full calendar</button></div>{upcoming.slice(0,12).map(a=><div className="admin-row" key={a.id}><div className="admin-row-main"><strong>{a.service_name||'Appointment'}</strong><span>{a.customer_name||'Customer'} · {a.scheduled_at?new Date(a.scheduled_at).toLocaleString():'Unscheduled'}</span></div><span className={`status-badge badge-${a.status==='completed'?'green':a.status==='cancelled'?'red':'blue'}`}>{prettyLabel(a.status)}</span></div>)}{!upcoming.length&&<div className="ns-empty compact">No upcoming jobs assigned.</div>}</section>}
   {tab==='activity'&&<section className="employee-activity-v25"><div className="profile-section-title-v25"><Activity/><div><strong>Recent Activity</strong><small>Operational activity currently available from appointments.</small></div></div>{assigned.slice(0,20).map(a=><div key={a.id}><Clock3 size={14}/><span><strong>{a.service_name}</strong><small>{a.customer_name||'Customer'} · {new Date(a.scheduled_at||a.created_at).toLocaleString()}</small></span><em>{prettyLabel(a.status)}</em></div>)}{!assigned.length&&<div className="ns-empty compact">No activity recorded yet.</div>}</section>}
  </div>
  {['employment','pay'].includes(tab)&&<div className="employee-profile-save-v25"><button className="btn-primary" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving...':'Save Changes'}</button></div>}
  <footer className="team-profile-actions">{e.email&&<a className="btn-outline" href={`mailto:${e.email}`}><Mail size={15}/>Email</a>}{e.phone&&<a className="btn-outline" href={`tel:${e.phone}`}><Phone size={15}/>Call</a>}<button className="btn-outline" onClick={onOpenMessages}><MessageCircle size={15}/>Message</button><button className="btn-outline" onClick={()=>onOpenCalendar(e.id)}><Calendar size={15}/>Calendar</button><button className="danger-button" onClick={()=>onDelete(e.id)}><Trash2 size={15}/>Permanently Delete</button></footer>
 </section></div>
}
