-- Exterior and interior details, each with three selves (Essential / Signature / Elite).
-- Also keep aliases for older service names so existing jobs still seed a checklist.

create or replace function public.ns_seed_job_checklist()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.field_status in ('started','in_progress') and old.field_status is distinct from new.field_status then
    if exists (select 1 from public.job_checklist_items where appointment_id = new.id) then
      return new;
    end if;
    insert into public.job_checklist_items(appointment_id,label,sort_order,required)
    select new.id,t.label,t.sort_order,t.required
    from public.job_checklist_templates t
    where t.active=true and (lower(t.service_name)=lower(new.service_name) or lower(t.service_name)=lower(coalesce(new.package_name,'')) or t.service_name='*')
    on conflict do nothing;
  end if;
  return new;
end $$;

insert into public.job_checklist_templates(service_name,label,sort_order,required) values
('Exterior Essential','Foam pre-wash',30,true),
('Exterior Essential','Hand wash & dry',40,true),
('Exterior Essential','Wheels & tires',50,true),
('Exterior Essential','Exterior glass',60,true),
('Exterior Essential','Spray sealant',70,true),
('Exterior Essential','Tire dressing',80,false),
('Exterior Signature','Foam pre-wash',30,true),
('Exterior Signature','Hand wash & dry',40,true),
('Exterior Signature','Wheels & tires',50,true),
('Exterior Signature','Bug & tar removal',60,true),
('Exterior Signature','Door jambs',70,true),
('Exterior Signature','Clay / decontamination',80,true),
('Exterior Signature','Exterior glass',90,true),
('Exterior Signature','Trim wipe',100,true),
('Exterior Signature','Spray sealant',110,true),
('Exterior Signature','Tire dressing',120,true),
('Exterior Elite','Foam pre-wash',30,true),
('Exterior Elite','Hand wash & dry',40,true),
('Exterior Elite','Wheels & tires',50,true),
('Exterior Elite','Bug & tar removal',60,true),
('Exterior Elite','Door jambs',70,true),
('Exterior Elite','Clay / decontamination',80,true),
('Exterior Elite','Paint enhancement pass',90,true),
('Exterior Elite','Engine bay wipe',100,false),
('Exterior Elite','Exterior glass',110,true),
('Exterior Elite','Trim restoration',120,true),
('Exterior Elite','Premium sealant',130,true),
('Exterior Elite','Final panel inspection',140,true),
('Interior Essential','Full vacuum',30,true),
('Interior Essential','Dash & console wipe',40,true),
('Interior Essential','Interior glass',50,true),
('Interior Essential','Floor mats',60,true),
('Interior Essential','Surface dressing',70,false),
('Interior Signature','Full vacuum',30,true),
('Interior Signature','Dash & console',40,true),
('Interior Signature','Door panels',50,true),
('Interior Signature','Leather / vinyl clean',60,true),
('Interior Signature','Interior glass',70,true),
('Interior Signature','Floor mats & trunk',80,true),
('Interior Signature','UV protectant',90,true),
('Interior Elite','Full vacuum',30,true),
('Interior Elite','Dash, console & vents',40,true),
('Interior Elite','Door panels & jambs',50,true),
('Interior Elite','Leather treatment',60,true),
('Interior Elite','Carpet extraction',70,true),
('Interior Elite','Crevice detail',80,true),
('Interior Elite','Interior glass',90,true),
('Interior Elite','Odor / pet-hair pass',100,false),
('Interior Elite','UV / ceramic interior protectant',110,true),
('Luxe Essential','Exterior · Foam pre-wash',30,true),
('Luxe Essential','Exterior · Hand wash & dry',40,true),
('Luxe Essential','Exterior · Wheels & tires',50,true),
('Luxe Essential','Exterior · Exterior glass',60,true),
('Luxe Essential','Exterior · Spray sealant',70,true),
('Luxe Essential','Exterior · Tire dressing',80,false),
('Luxe Essential','Interior · Full vacuum',90,true),
('Luxe Essential','Interior · Dash & console wipe',100,true),
('Luxe Essential','Interior · Interior glass',110,true),
('Luxe Essential','Interior · Floor mats',120,true),
('Luxe Essential','Interior · Surface dressing',130,false),
('Luxe Signature','Exterior · Foam pre-wash',30,true),
('Luxe Signature','Exterior · Hand wash & dry',40,true),
('Luxe Signature','Exterior · Wheels & tires',50,true),
('Luxe Signature','Exterior · Bug & tar removal',60,true),
('Luxe Signature','Exterior · Door jambs',70,true),
('Luxe Signature','Exterior · Clay / decontamination',80,true),
('Luxe Signature','Exterior · Exterior glass',90,true),
('Luxe Signature','Exterior · Trim wipe',100,true),
('Luxe Signature','Exterior · Spray sealant',110,true),
('Luxe Signature','Exterior · Tire dressing',120,true),
('Luxe Signature','Interior · Full vacuum',130,true),
('Luxe Signature','Interior · Dash & console',140,true),
('Luxe Signature','Interior · Door panels',150,true),
('Luxe Signature','Interior · Leather / vinyl clean',160,true),
('Luxe Signature','Interior · Interior glass',170,true),
('Luxe Signature','Interior · Floor mats & trunk',180,true),
('Luxe Signature','Interior · UV protectant',190,true),
('Luxe Elite','Exterior · Foam pre-wash',30,true),
('Luxe Elite','Exterior · Hand wash & dry',40,true),
('Luxe Elite','Exterior · Wheels & tires',50,true),
('Luxe Elite','Exterior · Bug & tar removal',60,true),
('Luxe Elite','Exterior · Door jambs',70,true),
('Luxe Elite','Exterior · Clay / decontamination',80,true),
('Luxe Elite','Exterior · Paint enhancement pass',90,true),
('Luxe Elite','Exterior · Engine bay wipe',100,false),
('Luxe Elite','Exterior · Exterior glass',110,true),
('Luxe Elite','Exterior · Trim restoration',120,true),
('Luxe Elite','Exterior · Premium sealant',130,true),
('Luxe Elite','Exterior · Final panel inspection',140,true),
('Luxe Elite','Interior · Full vacuum',150,true),
('Luxe Elite','Interior · Dash, console & vents',160,true),
('Luxe Elite','Interior · Door panels & jambs',170,true),
('Luxe Elite','Interior · Leather treatment',180,true),
('Luxe Elite','Interior · Carpet extraction',190,true),
('Luxe Elite','Interior · Crevice detail',200,true),
('Luxe Elite','Interior · Interior glass',210,true),
('Luxe Elite','Interior · Odor / pet-hair pass',220,false),
('Luxe Elite','Interior · UV / ceramic interior protectant',230,true),
('Paint Correction','Paint inspection',30,true),
('Paint Correction','Decontamination',40,true),
('Paint Correction','Machine polishing',50,true),
('Paint Correction','Gloss enhancement',60,true),
('Paint Correction','Panel-by-panel finish',70,true),
('Luxe Ceramic Coating','Paint preparation',30,true),
('Luxe Ceramic Coating','Chemical decontamination',40,true),
('Luxe Ceramic Coating','Clay treatment',50,true),
('Luxe Ceramic Coating','Coating application',60,true),
('Luxe Ceramic Coating','Cure inspection',70,true),
('Luxe Exterior Detail','Foam pre-wash',30,true),
('Luxe Exterior Detail','Hand wash & dry',40,true),
('Luxe Exterior Detail','Wheels & tires',50,true),
('Luxe Exterior Detail','Bug & tar removal',60,true),
('Luxe Exterior Detail','Door jambs',70,true),
('Luxe Exterior Detail','Clay / decontamination',80,true),
('Luxe Exterior Detail','Exterior glass',90,true),
('Luxe Exterior Detail','Trim wipe',100,true),
('Luxe Exterior Detail','Spray sealant',110,true),
('Luxe Exterior Detail','Tire dressing',120,true),
('Luxe Interior Detail','Full vacuum',30,true),
('Luxe Interior Detail','Dash & console',40,true),
('Luxe Interior Detail','Door panels',50,true),
('Luxe Interior Detail','Leather / vinyl clean',60,true),
('Luxe Interior Detail','Interior glass',70,true),
('Luxe Interior Detail','Floor mats & trunk',80,true),
('Luxe Interior Detail','UV protectant',90,true),
('Luxe Signature Detail','Exterior · Foam pre-wash',30,true),
('Luxe Signature Detail','Exterior · Hand wash & dry',40,true),
('Luxe Signature Detail','Exterior · Wheels & tires',50,true),
('Luxe Signature Detail','Exterior · Bug & tar removal',60,true),
('Luxe Signature Detail','Exterior · Door jambs',70,true),
('Luxe Signature Detail','Exterior · Clay / decontamination',80,true),
('Luxe Signature Detail','Exterior · Exterior glass',90,true),
('Luxe Signature Detail','Exterior · Trim wipe',100,true),
('Luxe Signature Detail','Exterior · Spray sealant',110,true),
('Luxe Signature Detail','Exterior · Tire dressing',120,true),
('Luxe Signature Detail','Interior · Full vacuum',130,true),
('Luxe Signature Detail','Interior · Dash & console',140,true),
('Luxe Signature Detail','Interior · Door panels',150,true),
('Luxe Signature Detail','Interior · Leather / vinyl clean',160,true),
('Luxe Signature Detail','Interior · Interior glass',170,true),
('Luxe Signature Detail','Interior · Floor mats & trunk',180,true),
('Luxe Signature Detail','Interior · UV protectant',190,true)
on conflict(service_name,label) do update set sort_order=excluded.sort_order,required=excluded.required,active=true;
