import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'npm:@supabase/supabase-js@2.57.4';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Client-Info, Apikey, X-Automation-Secret','Content-Type':'application/json'};
function serverKey(){const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(legacy)return legacy;const raw=Deno.env.get('SUPABASE_SECRET_KEYS');if(!raw)return'';try{const p=JSON.parse(raw);return p?.default||p?.service_role||p?.serviceRole||''}catch{return''}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const url=Deno.env.get('SUPABASE_URL')||'',key=serverKey(),sendgrid=Deno.env.get('SENDGRID_API_KEY')||'',fromEmail=Deno.env.get('SENDGRID_FROM_EMAIL')||'appointments@northsplash.com',fromName=Deno.env.get('SENDGRID_FROM_NAME')||'North Splash Auto Luxe';if(!url||!key)throw new Error('Supabase server credentials are missing.');
 const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
 const workerSecret=Deno.env.get('AUTOMATION_WORKER_SECRET')||'';
 const providedSecret=req.headers.get('X-Automation-Secret')||'';
 const scheduled=Boolean(workerSecret&&providedSecret&&providedSecret===workerSecret);
 if(!scheduled){
  const token=(req.headers.get('Authorization')||'').replace('Bearer ','');
  const {data:{user}}=await admin.auth.getUser(token);if(!user)throw new Error('Unauthorized');
  const {data:actor}=await admin.from('profiles').select('role,portal_role,permissions').eq('id',user.id).maybeSingle();
  if(!(actor?.role==='admin'||actor?.portal_role==='owner'||actor?.permissions?.['notifications.manage']))throw new Error('Automation access required.');
 }
 try{await admin.rpc('ns_release_expired_lead_cooldowns')}catch{}
 await queueDueEvents(admin);const limit=Math.max(1,Math.min(250,Number((await safeJson(req))?.limit||100)));const{data:events,error}=await admin.from('automation_events').select('*').eq('status','pending').lte('process_after',new Date().toISOString()).order('process_after').limit(limit);if(error)throw error;let processed=0,failed=0;
 for(const event of events||[]){try{await admin.from('automation_events').update({status:'processing',attempts:(event.attempts||0)+1}).eq('id',event.id);const{data:rules}=await admin.from('automation_rules').select('*').eq('trigger_event',event.event_key).eq('is_enabled',true);for(const rule of rules||[])await executeRule(admin,sendgrid,fromEmail,fromName,rule,event);await admin.from('automation_events').update({status:'processed',processed_at:new Date().toISOString(),error_message:null}).eq('id',event.id);processed++}catch(e){failed++;const attempts=Number(event.attempts||0)+1;const retry=attempts<3;await admin.from('automation_events').update({status:retry?'pending':'failed',error_message:e instanceof Error?e.message:String(e),process_after:retry?new Date(Date.now()+Math.min(30,Math.pow(2,attempts))*60000).toISOString():event.process_after}).eq('id',event.id)}}return json({success:true,processed,failed,queued:(events||[]).length,mode:scheduled?'scheduled':'manual'});
}catch(e){return json({error:e instanceof Error?e.message:String(e)},400)}});
async function safeJson(req:Request){try{return await req.clone().json()}catch{return{}}}
async function queueOnce(admin:any,event_key:string,entity_type:string,entity_id:string,payload:any,process_after:string){const{data}=await admin.from('automation_events').select('id').eq('event_key',event_key).eq('entity_id',entity_id).maybeSingle();if(!data)await admin.from('automation_events').insert({event_key,entity_type,entity_id,payload,status:'pending',process_after})}
async function queueDueEvents(admin:any){
 const now=new Date(),in25h=new Date(now.getTime()+25*3600000).toISOString();const{data:appointments}=await admin.from('appointments').select('id,user_id,customer_name,customer_email,service_name,vehicle_info,service_address,scheduled_at,status,price,completed_at,assigned_employee_id').gte('scheduled_at',now.toISOString()).lte('scheduled_at',in25h).not('status','in','("cancelled","completed")');
 for(const a of appointments||[]){const at=new Date(a.scheduled_at).getTime();const before24=new Date(at-24*3600000),before2=new Date(at-2*3600000);await queueOnce(admin,'appointment.reminder_24h','appointment',a.id,{...a,communication_event:'appointment_reminder_24h'},before24>now?before24.toISOString():now.toISOString());await queueOnce(admin,'appointment.reminder_2h','appointment',a.id,{...a,communication_event:'appointment_reminder_2h'},before2>now?before2.toISOString():now.toISOString())}
 const ninetyDaysAgo=new Date(now.getTime()-92*86400000).toISOString();const{data:completed}=await admin.from('appointments').select('id,user_id,customer_name,customer_email,service_name,vehicle_info,price,completed_at').eq('status','completed').gte('completed_at',ninetyDaysAgo).not('completed_at','is',null);
 for(const a of completed||[]){const done=new Date(a.completed_at).getTime();await queueOnce(admin,'job.review_due','appointment',a.id,{...a,communication_event:'review_request'},new Date(done+2*3600000).toISOString());await queueOnce(admin,'customer.rebook_30d','appointment',a.id,{...a,communication_event:'rebooking_30d'},new Date(done+30*86400000).toISOString());await queueOnce(admin,'customer.rebook_90d','appointment',a.id,{...a,communication_event:'rebooking_90d'},new Date(done+90*86400000).toISOString())}
 const{data:leads}=await admin.from('leads').select('id,assigned_employee_id,customer_name,address,follow_up_at,phone,email').lte('follow_up_at',now.toISOString()).not('status','in','("sold","lost","not_interested","do_not_knock")').limit(250);for(const lead of leads||[])await queueOnce(admin,'lead.follow_up_due','lead',lead.id,{...lead,message:`Follow up with ${lead.customer_name||lead.address||'lead'}`},now.toISOString());
}
async function executeRule(admin:any,sendgrid:string,fromEmail:string,fromName:string,rule:any,event:any){
 if(rule.action_type==='notification'){await admin.from('business_notifications').insert({target_employee_id:event.payload?.manager_employee_id||event.payload?.assigned_employee_id||null,target_portal_role:event.payload?.assigned_employee_id||event.payload?.manager_employee_id?null:'owner',title:rule.name,message:String(event.payload?.message||human(event.event_key)),notification_type:'automation',link:event.payload?.link||null});return}
 if(rule.action_type==='task'){await admin.from('business_tasks').insert({title:rule.name,description:String(event.payload?.message||human(event.event_key)),assigned_employee_id:event.payload?.manager_employee_id||event.payload?.assigned_employee_id||null,priority:event.payload?.priority||'normal',status:'open',due_at:event.payload?.due_at||null});return}
 if(rule.action_type==='email'){
  if(!sendgrid)throw new Error('SENDGRID_API_KEY is required for email automations.');const eventKey=event.payload?.communication_event||event.event_key;const{data:template}=await admin.from('communication_templates').select('*').eq('event_key',eventKey).eq('is_enabled',true).eq('email_enabled',true).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!template)return;let recipient=event.payload?.recipient_email||event.payload?.customer_email||'';if(!recipient&&event.payload?.user_id){const{data:p}=await admin.from('profiles').select('email').eq('id',event.payload.user_id).maybeSingle();recipient=p?.email||''}if(!recipient)return;
  const vars={...event.payload,customer_first_name:String(event.payload?.customer_name||'Customer').split(/\s+/)[0],service:event.payload?.service_name||'Detailing service',vehicle:event.payload?.vehicle_info||'Your vehicle',appointment_time:event.payload?.scheduled_at?new Date(event.payload.scheduled_at).toLocaleString('en-US',{weekday:'long',month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}):'',price:money(event.payload?.price),portal_link:'https://ns-auto-luxe-os.vercel.app/portal'};const subject=render(template.subject||'North Splash Update',vars),text=render(template.body||'',vars);
  const r=await fetch('https://api.sendgrid.com/v3/mail/send',{method:'POST',headers:{Authorization:`Bearer ${sendgrid}`,'Content-Type':'application/json'},body:JSON.stringify({personalizations:[{to:[{email:recipient}],subject}],from:{email:String(template.from_email||fromEmail).replace(/^.*<([^>]+)>.*$/,'$1').trim(),name:fromName},content:[{type:'text/plain',value:text},{type:'text/html',value:emailHtml(subject,text,vars)}]})});const raw=await r.text();if(!r.ok)throw new Error(raw||'SendGrid automation failed');await admin.from('communication_logs').insert({event_key:eventKey,audience:template.audience||'customer',recipient_email:recipient,from_email:fromEmail,subject,status:'sent',provider_id:r.headers.get('x-message-id'),sent_at:new Date().toISOString(),related_appointment_id:event.entity_type==='appointment'?event.entity_id:null});
 }
}
function emailHtml(subject:string,text:string,vars:any){return `<div style="background:#070707;padding:30px;font-family:Arial;color:#f5f5f0"><div style="max-width:620px;margin:auto;background:#0d0d0d;border:1px solid #292316;border-radius:16px;overflow:hidden"><div style="background:#13100a;color:white;padding:22px 26px"><b style="letter-spacing:3px">NORTH SPLASH</b><div style="color:#d9ad4a;font-size:11px;letter-spacing:4px">AUTO LUXE</div></div><div style="padding:28px"><h2>${escapeHtml(subject)}</h2><p style="line-height:1.65;color:#d4d4cf">${escapeHtml(text).replace(/\n/g,'<br/>')}</p><a href="${escapeHtml(vars.portal_link||'#')}" style="display:inline-block;margin-top:18px;padding:12px 18px;background:#d9ad4a;color:#080808;text-decoration:none;border-radius:8px;font-weight:800">VIEW APPOINTMENT</a></div></div></div>`}
function money(v:any){const n=Number(v||0);return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number.isFinite(n)?n:0)}
function human(v:string){return v.replaceAll('.',' ').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}function render(template:string,vars:any){return template.replace(/{{?\s*([\w.]+)\s*}?}/g,(_m,k)=>{const v=k.split('.').reduce((o:any,p:string)=>o?.[p],vars);return v==null?'':String(v)})}function escapeHtml(v:string){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c))}function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors})}
