import { useMemo, useState } from 'react';
import { DollarSign, TrendingUp, WalletCards, Settings2, ChevronDown, ChevronUp, CalendarDays, UserPlus, Save, RotateCcw, Pencil, X, Users, ReceiptText } from 'lucide-react';
import { buildOwnerPlan, ownerDate, ownerMoney, OwnerPlanningConfig, OwnerPlanWeek, OwnerWeekOverride } from '@/lib/ownerPlanning';
import { useOwnerPlanning } from '@/hooks/useOwnerPlanning';

function MiniBars({weeks,keyName}:{weeks:OwnerPlanWeek[];keyName:'revenue'|'netProfit'|'cash'|'payroll'}){const sample=weeks.filter((_,i)=>i%4===0);const max=Math.max(1,...sample.map(w=>Math.max(0,w[keyName])));return <div className="owner-profit-bars">{sample.map(w=><div key={w.n} title={`Week ${w.n}: ${ownerMoney(w[keyName])}`}><i style={{height:`${Math.max(3,Math.max(0,w[keyName])/max*100)}%`}}/><span>{w.n}</span></div>)}</div>}
function NumberField({label,value,onChange,suffix,step=1}:{label:string;value:number;onChange:(v:number)=>void;suffix?:string;step?:number}){return <label className="owner-edit-field"><span>{label}</span><div><input type="number" step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/>{suffix&&<small>{suffix}</small>}</div></label>}

export default function OwnerProfitTracker(){
 const state=useOwnerPlanning(); const {config,loading,saving,dirty,error,savedAt,update,setWeekOverride,clearWeekOverride,save,reset}=state;
 const [settings,setSettings]=useState(false); const [year,setYear]=useState<'all'|'y1'|'y2'>('all'); const [editWeek,setEditWeek]=useState<number|null>(null);
 const weeks=useMemo(()=>buildOwnerPlan(config),[config]);
 const shown=weeks.filter(w=>year==='all'||(year==='y1'?w.n<=52:w.n>52));
 const totals=shown.reduce((x,w)=>({revenue:x.revenue+w.revenue,payroll:x.payroll+w.payroll,operating:x.operating+w.operating,pre:x.pre+w.profitBeforeOwners,owners:x.owners+w.owner1+w.owner2,tax:x.tax+w.taxReserve,net:x.net+w.netProfit,jobs:x.jobs+w.jobs,extra:x.extra+w.extraCosts}),{revenue:0,payroll:0,operating:0,pre:0,owners:0,tax:0,net:0,jobs:0,extra:0});
 const final=shown.at(-1)||weeks.at(-1)!; const milestones=weeks.filter(w=>w.event||w.note);
 const summaries=useMemo(()=>{const group=(kind:'month'|'quarter'|'year')=>{const m=new Map<string,{label:string;revenue:number;owners:number;net:number;jobs:number}>();weeks.forEach(w=>{const y=w.start.getFullYear(),mo=w.start.getMonth();const key=kind==='month'?`${y}-${mo}`:kind==='quarter'?`${y}-Q${Math.floor(mo/3)+1}`:`${y}`;const label=kind==='month'?w.start.toLocaleDateString('en-US',{month:'long',year:'numeric'}):kind==='quarter'?`Q${Math.floor(mo/3)+1} ${y}`:`${y}`;const v=m.get(key)||{label,revenue:0,owners:0,net:0,jobs:0};v.revenue+=w.revenue;v.owners+=w.owner1+w.owner2;v.net+=w.netProfit;v.jobs+=w.jobs;m.set(key,v)});return [...m.values()]};return{monthly:group('month'),quarterly:group('quarter'),annual:group('year')}},[weeks]);
 const week=editWeek?weeks.find(w=>w.n===editWeek):null; const override=editWeek?config.weeklyOverrides[String(editWeek)]||{}:null;
 const setNum=(k:keyof OwnerPlanningConfig,v:number)=>update(k,v as never); const setO=(k:keyof OwnerWeekOverride,v:number|string|undefined)=>editWeek&&setWeekOverride(editWeek,{[k]:v});
 if(loading)return <div className="tab-content owner-profit-page"><div className="owner-loading">Loading shared owner profit plan…</div></div>;
 return <div className="tab-content owner-profit-page">
  <div className="owner-profit-head"><div><span className="eyebrow">OWNER ONLY · NORTH SPLASH AUTO LUXE</span><h1>2-Year Weekly Profit Tracker</h1><p>September 30, 2026 through September 30, 2028. Every major assumption and every individual week is editable, so this can become the operating plan rather than a fixed projection.</p></div><div className="owner-plan-actions"><button className="btn-outline" onClick={()=>setSettings(!settings)}><Settings2 size={17}/> Edit assumptions {settings?<ChevronUp size={15}/>:<ChevronDown size={15}/>}</button><button className="btn-primary" disabled={!dirty||saving} onClick={()=>void save()}><Save size={17}/>{saving?'Saving…':dirty?'Save changes':'Saved'}</button></div></div>
  {(error||savedAt)&&<div className={`owner-save-status ${error?'error':''}`}>{error||`Shared plan saved ${new Date(savedAt).toLocaleString()}`}</div>}
  <div className="owner-profit-flow"><b>Revenue</b><span>→</span><b>Operating Costs</b><span>→</span><b>Employee Payroll</b><span>→</span><b>Profit Before Owners</b><span>→</span><b>Owner Pay</b><span>→</span><b>Net Business Profit</b><span>→</span><b>Retained Cash</b></div>
  {settings&&<section className="owner-profit-settings"><div className="owner-profit-settings-head"><div><h3>Editable projection assumptions</h3><p>Change volume, staff, pay, costs, tax reserve, owner distributions and capacity. Use weekly overrides for one-off changes or a hand-built staffing plan.</p></div><button className="btn-outline" onClick={reset}><RotateCcw size={15}/> Reset defaults</button></div><div className="owner-profit-settings-grid">
   <NumberField label="Average ticket" value={config.avgTicket} onChange={v=>setNum('avgTicket',v)} suffix="$"/><NumberField label="Starting jobs / week" value={config.jobsPerOwnerWeek} onChange={v=>setNum('jobsPerOwnerWeek',v)}/><NumberField label="Weekly demand growth" value={config.leadGrowthPct} onChange={v=>setNum('leadGrowthPct',v)} suffix="%" step={0.05}/><NumberField label="Owner-operated weeks" value={config.ownerOperatedWeeks} onChange={v=>setNum('ownerOperatedWeeks',v)}/>
   <NumberField label="Starting detailers" value={config.startingDetailers} onChange={v=>setNum('startingDetailers',v)}/><NumberField label="Starting D2D reps" value={config.startingD2D} onChange={v=>setNum('startingD2D',v)}/><NumberField label="Starting managers" value={config.startingManagers} onChange={v=>setNum('startingManagers',v)}/><label className="owner-edit-field"><span>Automatic hiring</span><select value={config.autoHiringEnabled?'1':'0'} onChange={e=>setNum('autoHiringEnabled',Number(e.target.value))}><option value="1">On — trigger based</option><option value="0">Off — manual staffing</option></select></label>
   <NumberField label="Detailer wage" value={config.detailerWage} onChange={v=>setNum('detailerWage',v)} suffix="$ / hr"/><NumberField label="Detailer hours / week" value={config.detailerHoursPerWeek} onChange={v=>setNum('detailerHoursPerWeek',v)}/><NumberField label="Detailer capacity" value={config.detailerCapacityJobs} onChange={v=>setNum('detailerCapacityJobs',v)} suffix="jobs / week"/><NumberField label="First detailer trigger" value={config.hireDetailerAtJobs} onChange={v=>setNum('hireDetailerAtJobs',v)} suffix="jobs / week"/>
   <NumberField label="D2D weekly base" value={config.d2dBase} onChange={v=>setNum('d2dBase',v)} suffix="$"/><NumberField label="D2D commission" value={config.d2dCommissionPct} onChange={v=>setNum('d2dCommissionPct',v)} suffix="%"/><NumberField label="D2D capacity" value={config.d2dCapacityJobs} onChange={v=>setNum('d2dCapacityJobs',v)} suffix="jobs / rep"/><NumberField label="First D2D trigger" value={config.hireD2DAtJobs} onChange={v=>setNum('hireD2DAtJobs',v)} suffix="jobs / week"/>
   <NumberField label="Manager wage" value={config.managerWage} onChange={v=>setNum('managerWage',v)} suffix="$ / hr"/><NumberField label="Manager hours / week" value={config.managerHoursPerWeek} onChange={v=>setNum('managerHoursPerWeek',v)}/><NumberField label="Manager trigger" value={config.managerAtEmployees} onChange={v=>setNum('managerAtEmployees',v)} suffix="employees"/><NumberField label="Doors per booked job" value={config.doorsPerJob} onChange={v=>setNum('doorsPerJob',v)}/>
   <NumberField label="Supplies + variable costs" value={config.variableCostPct} onChange={v=>setNum('variableCostPct',v)} suffix="% revenue"/><NumberField label="Fixed weekly overhead" value={config.fixedWeekly} onChange={v=>setNum('fixedWeekly',v)} suffix="$"/><NumberField label="Tax reserve" value={config.taxReservePct} onChange={v=>setNum('taxReservePct',v)} suffix="% profit"/><NumberField label="Starting business cash" value={config.startingCash} onChange={v=>setNum('startingCash',v)} suffix="$"/>
   <NumberField label="Owner target minimum" value={config.ownerMinPay} onChange={v=>setNum('ownerMinPay',v)} suffix="$ / owner"/><NumberField label="Owner target maximum" value={config.ownerMaxPay} onChange={v=>setNum('ownerMaxPay',v)} suffix="$ / owner"/><NumberField label="Vehicle / equipment reserve" value={config.vehicleCost} onChange={v=>setNum('vehicleCost',v)} suffix="$"/><NumberField label="Reserve interval" value={config.vehicleReserveEveryWeeks} onChange={v=>setNum('vehicleReserveEveryWeeks',v)} suffix="weeks; 0 disables"/>
  </div></section>}
  <div className="owner-profit-filter"><button className={year==='all'?'active':''} onClick={()=>setYear('all')}>Full 2 Years</button><button className={year==='y1'?'active':''} onClick={()=>setYear('y1')}>Year 1</button><button className={year==='y2'?'active':''} onClick={()=>setYear('y2')}>Year 2</button><span>{shown.length} weekly intervals</span></div>
  <div className="owner-profit-kpis"><div><DollarSign/><span>Revenue</span><strong>{ownerMoney(totals.revenue)}</strong><small>{totals.jobs.toLocaleString()} planned details</small></div><div><TrendingUp/><span>Profit before owners</span><strong>{ownerMoney(totals.pre)}</strong><small>after operating costs + payroll</small></div><div><WalletCards/><span>Owner distributions</span><strong>{ownerMoney(totals.owners)}</strong><small>{ownerMoney(totals.owners/2)} average per 50% owner</small></div><div><DollarSign/><span>Net retained profit</span><strong>{ownerMoney(totals.net)}</strong><small>{ownerMoney(final.cash)} ending cash</small></div></div>
  <div className="owner-profit-charts"><section><div className="owner-profit-panel-title"><div><span className="eyebrow">GROWTH</span><h3>Weekly Revenue</h3></div><strong>{ownerMoney(totals.revenue)}</strong></div><MiniBars weeks={shown} keyName="revenue"/></section><section><div className="owner-profit-panel-title"><div><span className="eyebrow">CASH</span><h3>Retained Cash</h3></div><strong>{ownerMoney(final.cash)}</strong></div><MiniBars weeks={shown} keyName="cash"/></section></div>
  <div className="owner-profit-split"><section><div className="owner-profit-panel-title"><div><span className="eyebrow">OWNERSHIP</span><h3>50 / 50 Owner Distribution</h3></div></div><div className="owner-split-cards"><div><span>Owner 1</span><strong>50%</strong><small>{ownerMoney(totals.owners/2)} projected distributions</small></div><div><span>Owner 2</span><strong>50%</strong><small>{ownerMoney(totals.owners/2)} projected distributions</small></div></div><p className="owner-profit-note">Owner distributions can be overridden independently week by week. The model is planning software, not tax or accounting advice.</p></section><section><div className="owner-profit-panel-title"><div><span className="eyebrow">SCALE PLAN</span><h3>Hiring, Cost & Equipment Milestones</h3></div></div><div className="owner-profit-milestones">{milestones.slice(0,14).map(w=><div key={w.n}><span><UserPlus size={15}/></span><div><strong>Week {w.n} · {w.note||w.event}</strong><small>{ownerDate(w.start)} · {w.jobs} jobs · {ownerMoney(w.revenue)} revenue</small></div></div>)}</div></section></div>
  <section className="owner-profit-table-card owner-profit-summary-card"><div className="owner-profit-panel-title"><div><span className="eyebrow">ROLLUPS</span><h3>Monthly · Quarterly · Annual</h3></div></div><div className="owner-profit-summary-grid"><div><h4>Annual</h4>{summaries.annual.map(x=><div className="owner-profit-summary-row" key={x.label}><span>{x.label}<small>{x.jobs} jobs</small></span><b>{ownerMoney(x.revenue)}<small>{ownerMoney(x.net)} retained profit</small></b></div>)}</div><div><h4>Quarterly</h4>{summaries.quarterly.map(x=><div className="owner-profit-summary-row" key={x.label}><span>{x.label}<small>{x.jobs} jobs</small></span><b>{ownerMoney(x.revenue)}<small>{ownerMoney(x.net)} retained profit</small></b></div>)}</div><div><h4>Monthly</h4><div className="owner-profit-month-scroll">{summaries.monthly.map(x=><div className="owner-profit-summary-row" key={x.label}><span>{x.label}<small>{x.jobs} jobs</small></span><b>{ownerMoney(x.revenue)}<small>{ownerMoney(x.net)} retained profit</small></b></div>)}</div></div></div></section>
  <section className="owner-profit-table-card"><div className="owner-profit-panel-title"><div><span className="eyebrow">WEEK BY WEEK · FULLY EDITABLE</span><h3>Day One → Year Two</h3></div><span className="owner-profit-date"><CalendarDays size={15}/> Sep 30, 2026 — Sep 30, 2028</span></div><div className="owner-profit-mobile-weeks">{shown.map(w=><details key={w.n} className={`owner-profit-week-card ${w.overridden?'overridden':''}`}><summary><div><b>Week {w.n}{w.overridden?' · Custom':''}</b><span>{ownerDate(w.start)} — {ownerDate(w.end)}</span></div><strong>{ownerMoney(w.revenue)}</strong></summary><div className="owner-profit-week-grid"><span>Jobs<b>{w.jobs}</b></span><span>Team<b>{w.employeeCount===0?'Owners':`${w.detailers}D · ${w.d2d}S · ${w.managers}M`}</b></span><span>Operating<b>{ownerMoney(w.operating)}</b></span><span>Payroll<b>{ownerMoney(w.payroll)}</b></span><span>Pre-owner profit<b>{ownerMoney(w.profitBeforeOwners)}</b></span><span>Owner 1<b>{ownerMoney(w.owner1)}</b></span><span>Owner 2<b>{ownerMoney(w.owner2)}</b></span><span>Tax reserve<b>{ownerMoney(w.taxReserve)}</b></span><span>Net profit<b>{ownerMoney(w.netProfit)}</b></span><span>Retained cash<b>{ownerMoney(w.cash)}</b></span></div>{(w.note||w.event)&&<p className="owner-week-event">{w.note||w.event}</p>}<button className="owner-mobile-edit-week" onClick={()=>setEditWeek(w.n)}><Pencil size={14}/> Edit this week</button></details>)}</div><div className="owner-profit-table-wrap"><table className="owner-profit-table"><thead><tr><th>Week</th><th>Dates</th><th>Jobs</th><th>Team</th><th>Revenue</th><th>Operating</th><th>Payroll</th><th>Pre-owner Profit</th><th>Owner 1</th><th>Owner 2</th><th>Tax Reserve</th><th>Net Profit</th><th>Cash</th><th>Edit</th></tr></thead><tbody>{shown.map(w=><tr key={w.n} className={w.overridden?'overridden':''}><td><b>{w.n}</b>{(w.note||w.event)&&<small className="owner-week-event">{w.note||w.event}</small>}</td><td>{ownerDate(w.start)}<small>to {ownerDate(w.end)}</small></td><td>{w.jobs}</td><td>{w.employeeCount===0?'Owners only':`${w.detailers}D · ${w.d2d}S · ${w.managers}M`}</td><td>{ownerMoney(w.revenue)}</td><td>{ownerMoney(w.operating)}</td><td>{ownerMoney(w.payroll)}</td><td>{ownerMoney(w.profitBeforeOwners)}</td><td>{ownerMoney(w.owner1)}</td><td>{ownerMoney(w.owner2)}</td><td>{ownerMoney(w.taxReserve)}</td><td>{ownerMoney(w.netProfit)}</td><td><b>{ownerMoney(w.cash)}</b></td><td><button className="owner-table-edit" onClick={()=>setEditWeek(w.n)}><Pencil size={14}/></button></td></tr>)}</tbody></table></div></section>
  {editWeek&&week&&override&&<div className="owner-week-modal-backdrop" onClick={()=>setEditWeek(null)}><div className="owner-week-modal owner-week-modal-wide" onClick={e=>e.stopPropagation()}><div className="owner-week-modal-head"><div><span className="eyebrow">WEEK {editWeek}</span><h3>Edit jobs, employees, costs & owner pay</h3><p>Blank fields use the model. Enter a number to force that value for this week.</p></div><button onClick={()=>setEditWeek(null)}><X size={20}/></button></div><div className="owner-week-edit-grid">
   {([['jobs','Details / jobs',week.jobs],['avgTicket','Average ticket',week.avgTicket],['detailers','Detailers',week.detailers],['d2d','D2D reps',week.d2d],['managers','Managers',week.managers],['detailerWage','Detailer wage',config.detailerWage],['d2dBase','D2D weekly base',config.d2dBase],['d2dCommissionPct','D2D commission %',config.d2dCommissionPct],['managerWage','Manager wage',config.managerWage],['variableCostPct','Variable costs %',config.variableCostPct],['fixedWeekly','Fixed weekly costs',config.fixedWeekly],['extraCosts','Extra one-time costs',week.extraCosts],['taxReservePct','Tax reserve %',config.taxReservePct],['owner1Pay','Owner 1 pay',week.owner1],['owner2Pay','Owner 2 pay',week.owner2],['doors','D2D doors',week.doors]] as const).map(([key,label,current])=><label key={key}><span>{label}<small>Model: {typeof current==='number'?current.toLocaleString():current}</small></span><input type="number" placeholder="Use model" value={(override as any)[key]??''} onChange={e=>setO(key,e.target.value===''?undefined:Number(e.target.value))}/></label>)}
   <label className="owner-week-note"><span>Owner note / milestone</span><textarea value={override.note||''} onChange={e=>setO('note',e.target.value||undefined)} placeholder="Example: second van, major ad spend, seasonal slowdown…"/></label>
  </div><div className="owner-week-preview"><Users size={18}/><span>{week.jobs} jobs · {week.employeeCount} employees</span><ReceiptText size={18}/><span>{ownerMoney(week.operating)} operating · {ownerMoney(week.payroll)} payroll</span></div><div className="owner-week-modal-actions"><button className="btn-outline" onClick={()=>{clearWeekOverride(editWeek);setEditWeek(null)}}>Clear override</button><button className="btn-primary" onClick={()=>{setEditWeek(null);void save()}}><Save size={15}/> Save shared plan</button></div></div></div>}
 </div>
}
